apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/bolasto/my-app

        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: argocd

spec:
  selector:
    app: myapp
  ports:
  - name: http
    port: 8080
    targetPort: 80
  type: LoadBalancer
