apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd

spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/Bolasto/altschool-final-exam.git
      targetRevision: HEAD
      ref: myRepository
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: 19.7.2
      helm:
        valueFiles:
          - $myRepository/my-argocd-apps/values/prometheus.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
